id: circleci-orbs
hints:
- "Follow the instructions in the [CircleCI documentation](https://circleci.com/docs/orb-intro/) for more information on how to do this."
- "See how to use the Node orb here: https://circleci.com/docs/language-javascript/"
- >
  Use this params for `node/test` jobs:
    app-dir: frontend
    version: "16.18"
    pkg-manager: yarn
startFlow:
  do:
  - actionId: github_commit_file
    params:
      file: ${config.yml}
      path: .circleci
  - actionId: github_commit_file
    params:
      file: ${DeleteButton.js}
      path: frontend/src/components/Item
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "I wanted to start you off on a small project to get you up to speed on how we work here."
      - text: "One of our expert developers suggested that we should migrate our CircleCI configuration to an orb. Orbs are reusable packages of CircleCI configuration that can be shared and reused across projects."
      - text: "Migrating to an orb can make your configuration easier to maintain and share with others. Plus, it's just generally considered a best practice these days."
      - text: "Please replace the .circleci/config.yml content to references an orb. Once you've done that, push it and make sure the task passes in CircleCI."
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_workflow_complete_success:
          if:
            conditions:
            - conditionId: github_does_file_contain
              params:
                fileName: ".circleci/config.yml"
                regex: "orbs:"
            then:
              do:
              - actionId: github_pr_comment
                params:
                  person: keen
                  message: "Sweet, now we're able to use the orb in our config. Just make sure the tasks is succesfully run on CircleCI"
              - actionId: finish_step
            else:
              do:
              - actionId: github_pr_comment
                params:
                  person: keen
                  message: "Are you sure you've replaced the config with an orb?"
