id: circleci-lint
hints:
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Now that we have Node orb configured, we shuold be able to easily add linting check as part of the checks"
      - text: "Add another step to run `yarn lint` as part of the CI"
      - text: "Lint is a very usefull tool to format the code in an automatic way to make sure we're all aligned."
trigger:
  type: circleci_event_received
  params:
    type: job-completed
  flowNode:
    if:
      conditions:
      - conditionId: is_truthy
        params:
          value: ${outputs.job?.status === 'failed'}
      - conditionId: github_does_file_contain
        params:
          branch: ${outputs.pipeline?.vcs?.branch}
          fileName: ".circleci/config.yml"
          regex: "lint"
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Great, I think this will save us some time on formatting comments as part of the code review"
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Hmmmm, not sure I see where you run the lint task"
