id: circleci-prettier
hints:
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "I see that the CI process detected some problems with out code, how about fixing it so we'll be able to merge the changes?"
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_workflow_complete_success:
          if:
            conditions:
            - conditionId: github_is_file_modified
              params:
                fileName: "frontend/src/components/Item/DeleteButton.js"
            then:
              do:
              - actionId: github_pr_comment
                params:
                  person: keen
                  message: "Nice! Now you can merge it and small issues like this hopefully won't bother us anymore"
            else:
              do:
              - actionId: github_pr_comment
                params:
                  person: keen
                  message: "I see the checks work but can see that you fix the relevant file"

        github_pr_merged:
          do:
          - actionId: finish_step
