id: circleci-prettier
hints:
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Now we want to levarage prettier to fix some linting problem if they find ones, and auto commit those."
      - text: "For this can run `yarn prettier" with `write` mode to make sure it'll fix all the problematic files."
      - text: "Add this to our CI process and see they fix any files automatically"
trigger:
  type: github_pr_lifecycle_status
    switch:
      key: "${eventType}"
      cases:
        github_pr_workflow_complete_success:
          if:
            conditions:
            - conditionId: github_does_file_contain
              params:
                fileName: ".circleci/config.yml"
                regex: " -w | --write "
            - conditionId: github_is_file_modified
              params:
                fileName: "frontend/src/components/Item/DeleteButton.js"
            then:
              do:
              - actionId: github_pr_comment
                params:
                  person: keen
                  message: "Prettier ✅"
            else:
              do:
              - actionId: github_pr_comment
                params:
                  person: keen
                  message: "Prettier ❌"
