id: circleci-fix-error
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "OK, so seemse like it doesn't find the package.json in the frontend directory, so I guess it doesn't run the the right location"
        delay: 1000
      - text: "Can you try to make it run on the frontend directory? :instruction[Change it and push the code and see if the task running succefully]"
        delay: 1000
trigger:
  type: circleci_event_received
  params: 
    type: workflow-completed
  flowNode:
      if:
        conditions:
        - conditionId: text_contains_strings
          params:
            text: ${outputs.workflow.status}
            strings:
            - success
      then:
        do:
        - actionId: bot_message
            params:
              person: keen
              messages:
              - text: "Cool, I see green!"
              - delay: 2000
        - actionId: finish_step
